# Generated by Django 3.1 on 2021-04-18 14:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ep', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='RecyclingData',
            new_name='PlasticData',
        ),
        migrations.AlterField(
            model_name='addtocart',
            name='cart_date',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='plasticproduct',
            name='pproduct_date',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='recycleproduct',
            name='rproduct_date',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
